import type { PromptInput } from '@promptrpp/contracts'

export const defaultPromptInput: PromptInput = {
  documentType: 'rpp',
  outputLevel: 'sangat-rinci',
  curriculum: 'Kurikulum Merdeka',
  subject: 'Matematika',
  level: 'SMP/MTs',
  phase: 'D',
  classroom: '8',
  semester: '1',
  topic: '',
  locale: '',
  meetings: 1,
  jpPerMeeting: 2,
  minutesPerJp: 40,
  cp: '',
  tp: '',
  initialCompetence: '',
  studentCharacteristics: '',
  dimensions: [],
  pedagogicalPractice: 'Inkuiri terbimbing',
  localContext: '',
  partnership: '',
  learningEnvironment: '',
  digitalUse: '',
  crossDiscipline: '',
  resources: '',
  assessmentFocus: 'Campuran sesuai kebutuhan',
  assessmentProduct: '',
  mediaFormat: '',
  preferences: {
    assumeMissing: true,
    differentiation: true,
    literacyNumeracy: true,
    socialEmotional: true,
    diagnostic: true,
    formative: true,
    asLearning: true,
    summative: false,
    stagedOutput: true,
  },
}
